const loginKeys = {
  SAVE_TOKEN: 'SAVE_TOKEN',
  LOGIN: 'LOGIN',
  SAVE_LOGIN: 'SAVE_LOGIN',
  ERROR: 'ERROR',
  LOGOUT: 'LOGOUT',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN',
  SAVE_SOCIAL_LOGIN: 'SAVE_SOCIAL_LOGIN',
  PAYMENT: 'PAYMENT',
  SAVE_PAYMENT: 'SAVE_PAYMENT',
  SAVE_CALL:'SAVE_CALL',
  CALL_DATA:'CALL_DATA',

};

export default loginKeys;
